local data = {
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 5 }, { item = "Citrome Powder", count = 5 } },
    products = { { item = "Canned Citrome (C)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 1 }, { item = "Clean Water", count = 1 } },
    products = { { item = "Amethyst Bottle (Clean Water)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 1 }, { item = "Precipitation Acid", count = 1 } },
    products = { { item = "Amethyst Bottle (Precipitation Acid)", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 10 }, { item = "Citrome Powder", count = 10 } },
    products = { { item = "Canned Citrome (B)", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 10 }, { item = "Ground Citrome Powder", count = 10 } },
    products = { { item = "Canned Citrome (A)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 1 }, { item = "Sewage", count = 1 } },
    products = { { item = "Amethyst Bottle (Sewage)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 1 }, { item = "Jincao Solution", count = 1 } },
    products = { { item = "Amethyst Bottle (Jincao Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 1 }, { item = "Yazhen Solution", count = 1 } },
    products = { { item = "Amethyst Bottle (Yazhen Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 1 }, { item = "Liquid Xiranite", count = 1 } },
    products = { { item = "Amethyst Bottle (Liquid Xiranite)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 1 }, { item = "Liquid Heavy Xiranite", count = 1 } },
    products = { { item = "Amethyst Bottle (Liquid Heavy Xiranite)", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 5 }, { item = "Buckflower Powder", count = 5 } },
    products = { { item = "Buck Capsule (C)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 1 }, { item = "Xircon Effluent", count = 1 } },
    products = { { item = "Amethyst Bottle (Xircon Effluent)", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 10 }, { item = "Buckflower Powder", count = 10 } },
    products = { { item = "Buck Capsule (B)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 1 }, { item = "Inert Xircon Effluent", count = 1 } },
    products = { { item = "Amethyst Bottle (Inert Xircon Effluent)", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 10 }, { item = "Ground Buckflower Powder", count = 10 } },
    products = { { item = "Buck Capsule (A)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 1 }, { item = "Cuprium Solution", count = 1 } },
    products = { { item = "Amethyst Bottle (Cuprium Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Bottle", count = 1 }, { item = "Hetonite Solution", count = 1 } },
    products = { { item = "Amethyst Bottle (Hetonite Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cryston Bottle", count = 1 }, { item = "Clean Water", count = 1 } },
    products = { { item = "Cryston Bottle (Clean Water)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cryston Bottle", count = 1 }, { item = "Precipitation Acid", count = 1 } },
    products = { { item = "Cryston Bottle (Precipitation Acid)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cryston Bottle", count = 1 }, { item = "Sewage", count = 1 } },
    products = { { item = "Cryston Bottle (Sewage)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cryston Bottle", count = 1 }, { item = "Jincao Solution", count = 1 } },
    products = { { item = "Cryston Bottle (Jincao Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cryston Bottle", count = 1 }, { item = "Yazhen Solution", count = 1 } },
    products = { { item = "Cryston Bottle (Yazhen Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cryston Bottle", count = 1 }, { item = "Liquid Xiranite", count = 1 } },
    products = { { item = "Cryston Bottle (Liquid Xiranite)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cryston Bottle", count = 1 }, { item = "Liquid Heavy Xiranite", count = 1 } },
    products = { { item = "Cryston Bottle (Liquid Heavy Xiranite)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cryston Bottle", count = 1 }, { item = "Xircon Effluent", count = 1 } },
    products = { { item = "Cryston Bottle (Xircon Effluent)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cryston Bottle", count = 1 }, { item = "Inert Xircon Effluent", count = 1 } },
    products = { { item = "Cryston Bottle (Inert Xircon Effluent)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cryston Bottle", count = 1 }, { item = "Cuprium Solution", count = 1 } },
    products = { { item = "Cryston Bottle (Cuprium Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cryston Bottle", count = 1 }, { item = "Hetonite Solution", count = 1 } },
    products = { { item = "Cryston Bottle (Hetonite Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 1 }, { item = "Clean Water", count = 1 } },
    products = { { item = "Ferrium Bottle (Clean Water)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 1 }, { item = "Precipitation Acid", count = 1 } },
    products = { { item = "Ferrium Bottle (Precipitation Acid)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 1 }, { item = "Sewage", count = 1 } },
    products = { { item = "Ferrium Bottle (Sewage)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 1 }, { item = "Jincao Solution", count = 1 } },
    products = { { item = "Ferrium Bottle (Jincao Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 1 }, { item = "Yazhen Solution", count = 1 } },
    products = { { item = "Ferrium Bottle (Yazhen Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 1 }, { item = "Liquid Xiranite", count = 1 } },
    products = { { item = "Ferrium Bottle (Liquid Xiranite)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 1 }, { item = "Liquid Heavy Xiranite", count = 1 } },
    products = { { item = "Ferrium Bottle (Liquid Heavy Xiranite)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 1 }, { item = "Xircon Effluent", count = 1 } },
    products = { { item = "Ferrium Bottle (Xircon Effluent)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 1 }, { item = "Inert Xircon Effluent", count = 1 } },
    products = { { item = "Ferrium Bottle (Inert Xircon Effluent)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 1 }, { item = "Cuprium Solution", count = 1 } },
    products = { { item = "Ferrium Bottle (Cuprium Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Bottle", count = 1 }, { item = "Hetonite Solution", count = 1 } },
    products = { { item = "Ferrium Bottle (Hetonite Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 1 }, { item = "Clean Water", count = 1 } },
    products = { { item = "Steel Bottle (Clean Water)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 1 }, { item = "Precipitation Acid", count = 1 } },
    products = { { item = "Steel Bottle (Precipitation Acid)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 1 }, { item = "Sewage", count = 1 } },
    products = { { item = "Steel Bottle (Sewage)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 1 }, { item = "Jincao Solution", count = 1 } },
    products = { { item = "Steel Bottle (Jincao Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 1 }, { item = "Yazhen Solution", count = 1 } },
    products = { { item = "Steel Bottle (Yazhen Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 1 }, { item = "Liquid Xiranite", count = 1 } },
    products = { { item = "Steel Bottle (Liquid Xiranite)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 1 }, { item = "Liquid Heavy Xiranite", count = 1 } },
    products = { { item = "Steel Bottle (Liquid Heavy Xiranite)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 1 }, { item = "Xircon Effluent", count = 1 } },
    products = { { item = "Steel Bottle (Xircon Effluent)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 1 }, { item = "Inert Xircon Effluent", count = 1 } },
    products = { { item = "Steel Bottle (Inert Xircon Effluent)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 1 }, { item = "Cuprium Solution", count = 1 } },
    products = { { item = "Steel Bottle (Cuprium Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Bottle", count = 1 }, { item = "Hetonite Solution", count = 1 } },
    products = { { item = "Steel Bottle (Hetonite Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Bottle", count = 1 }, { item = "Clean Water", count = 1 } },
    products = { { item = "Cuprium Bottle (Clean Water)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Bottle", count = 1 }, { item = "Precipitation Acid", count = 1 } },
    products = { { item = "Cuprium Bottle (Precipitation Acid)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Bottle", count = 1 }, { item = "Sewage", count = 1 } },
    products = { { item = "Cuprium Bottle (Sewage)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Bottle", count = 1 }, { item = "Jincao Solution", count = 1 } },
    products = { { item = "Cuprium Bottle (Jincao Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Bottle", count = 1 }, { item = "Yazhen Solution", count = 1 } },
    products = { { item = "Cuprium Bottle (Yazhen Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Bottle", count = 1 }, { item = "Liquid Xiranite", count = 1 } },
    products = { { item = "Cuprium Bottle (Liquid Xiranite)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Bottle", count = 1 }, { item = "Liquid Heavy Xiranite", count = 1 } },
    products = { { item = "Cuprium Bottle (Liquid Heavy Xiranite)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Bottle", count = 1 }, { item = "Xircon Effluent", count = 1 } },
    products = { { item = "Cuprium Bottle (Xircon Effluent)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Bottle", count = 1 }, { item = "Inert Xircon Effluent", count = 1 } },
    products = { { item = "Cuprium Bottle (Inert Xircon Effluent)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Bottle", count = 1 }, { item = "Cuprium Solution", count = 1 } },
    products = { { item = "Cuprium Bottle (Cuprium Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Bottle", count = 1 }, { item = "Hetonite Solution", count = 1 } },
    products = { { item = "Cuprium Bottle (Hetonite Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Hetonite Bottle", count = 1 }, { item = "Clean Water", count = 1 } },
    products = { { item = "Hetonite Bottle (Clean Water)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Hetonite Bottle", count = 1 }, { item = "Precipitation Acid", count = 1 } },
    products = { { item = "Hetonite Bottle (Precipitation Acid)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Hetonite Bottle", count = 1 }, { item = "Sewage", count = 1 } },
    products = { { item = "Hetonite Bottle (Sewage)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Hetonite Bottle", count = 1 }, { item = "Jincao Solution", count = 1 } },
    products = { { item = "Hetonite Bottle (Jincao Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Hetonite Bottle", count = 1 }, { item = "Yazhen Solution", count = 1 } },
    products = { { item = "Hetonite Bottle (Yazhen Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Hetonite Bottle", count = 1 }, { item = "Liquid Xiranite", count = 1 } },
    products = { { item = "Hetonite Bottle (Liquid Xiranite)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Hetonite Bottle", count = 1 }, { item = "Liquid Heavy Xiranite", count = 1 } },
    products = { { item = "Hetonite Bottle (Liquid Heavy Xiranite)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Hetonite Bottle", count = 1 }, { item = "Xircon Effluent", count = 1 } },
    products = { { item = "Hetonite Bottle (Xircon Effluent)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Hetonite Bottle", count = 1 }, { item = "Inert Xircon Effluent", count = 1 } },
    products = { { item = "Hetonite Bottle (Inert Xircon Effluent)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Hetonite Bottle", count = 1 }, { item = "Cuprium Solution", count = 1 } },
    products = { { item = "Hetonite Bottle (Cuprium Solution)", count = 1 } },
},
{
    time = 2,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Hetonite Bottle", count = 1 }, { item = "Hetonite Solution", count = 1 } },
    products = { { item = "Hetonite Bottle (Hetonite Solution)", count = 1 } },
},
{
    time = 10,
    mode = "Fluid",
    event = false,
    eventName = "",
    ingredients = { { item = "Experimental Heavy Xiranite Bottle", count = 1 }, { item = "Yazhen Solution", count = 5 } },
    products = { { item = "Experimental Heavy Xiranite Bottle (Yazhen Solution)", count = 1 } },
},
}

for _, v in ipairs(data) do
    v.facility = "Filling Unit"
end

return data