local data = {
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Part", count = 5 }, { item = "Aketine Powder", count = 1 } },
    products = { { item = "Industrial Explosive", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Amethyst Part", count = 5 }, { item = "Originium Powder", count = 10 } },
    products = { { item = "LC Valley Battery", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Part", count = 10 }, { item = "Originium Powder", count = 15 } },
    products = { { item = "SC Valley Battery", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Steel Part", count = 10 }, { item = "Dense Originium Powder", count = 15 } },
    products = { { item = "HC Valley Battery", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Part", count = 10 }, { item = "Ferrium Bottle (Yazhen Solution)", count = 5 } },
    products = { { item = "Yazhen Syringe (C)", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Part", count = 10 }, { item = "Cuprium Bottle (Yazhen Solution)", count = 5 } },
    products = { { item = "Yazhen Syringe (A)", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Ferrium Part", count = 10 }, { item = "Ferrium Bottle (Jincao Solution)", count = 5 } },
    products = { { item = "Jincao Drink", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Cuprium Part", count = 10 }, { item = "Cuprium Bottle (Jincao Solution)", count = 5 } },
    products = { { item = "Jincao Tea", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Xiranite", count = 5 }, { item = "Dense Originium Powder", count = 15 } },
    products = { { item = "LC Wuling Battery", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = false,
    eventName = "",
    ingredients = { { item = "Xircon", count = 5 }, { item = "Dense Originium Powder", count = 20 } },
    products = { { item = "SC Wuling Battery", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = true,
    eventName = "Palm-Top Savior",
    ingredients = { { item = "Experimental Heavy Xiranite Part", count = 1 }, { item = "Hetonite", count = 1 } },
    products = { { item = "Experimental Xiran-Hue Atomizer", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = true,
    eventName = "Palm-Top Savior",
    ingredients = { { item = "Experimental Xiranite Bottle", count = 5 }, { item = "Experimental Xiranite Part", count = 5 } },
    products = { { item = "Xiranite Gourd", count = 1 } },
},
{
    time = 10,
    mode = "Solid",
    event = true,
    eventName = "Palm-Top Savior",
    ingredients = { { item = "Experimental Heavy Xiranite Bottle (Yazhen Solution)", count = 1 }, { item = "Experimental Xiran-Hue Atomizer", count = 1 } },
    products = { { item = "Xiranite Jade Gourd", count = 1 } },
},
}

for _, v in ipairs(data) do
    v.facility = "Packaging Unit"
end

return data